
server:
  port: 8180
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahmood-shamieh/MICRO-SERVICES-CONFIGURATION
          clone-on-start: true